### ISSUE TITLE
get dynamic resources to co-exist with the static assets without /wash namespace

### ISSUE THREAD

**Issue by andrewarrow** [andrewarrow/web-wash#1]
line 21 of https://github.com/andrewarrow/web-wash/blob/master/deploy/config.yml
server:
  rootPath: '/wash'

line 25 of https://github.com/andrewarrow/web-wash/blob/master/src/team/higher/web/MainApplication.kt

bootstrap.addBundle(AssetsBundle("/assets", "/", "index.html"))

allows all the assets here:

https://github.com/andrewarrow/web-wash/tree/master/resources/main/assets

to be served by the normal web server at the root path so "/images/foo.jpg" works or "/css/style.css" etc.

And it also serves that first index.html page for just root "/" path.

The problem is in resources like:

https://github.com/andrewarrow/web-wash/blob/master/src/team/higher/web/resource/DashboardResource.kt

where I say

@Path("/dashboard")

the final url is /wash/dashboard

there is always this "/wash" in front of everything to give me a namespace for the dynamic resources to co-exist with the static assets.

**Comment by psamsotha** [comment]
As mentioned in [this SO post][1], jersey has a couple properties you can set the that will allow Jersey to forward requests to a different servlet, namely

```java
ServletProperties.FILTER_STATIC_CONTENT_REGEX
ServletProperties.FILTER_FORWARD_ON_404
```

The former allowing you to specify a regex for all the paths you want it to forward, for example a regex matching all the static files. The latter will forward all requests for endpoints it cannot find (all your Jersey endpoints).

This forwarding is needed because if you use the default mapping, with Jersey being mapped to `/*`, then it will hog up all requests, and the servlet that handles the static content would be able to be reached.

The problem with this though (especially with Dropwizard) is that to make it work, Jersey needs to be configured as a servlet _Filter_, rather than a _Servlet_. The Jersey application can be configured to be run as either, but Dropwizard being an opinionated framework, doesn't make this easy, if at all possible. You would need to some way disable the default servlet configuration and manually register Jersey a Filter. I know how you could do the latter, not sure about the former. Not even sure it would be worth the trouble.

If the URLs really bug you, maybe open feature request with Dropwizard that would add a configuration option to configure Jersey as a Filter.

[1]: https://stackoverflow.com/a/29670751/2587435

**Comment by andrewarrow** [comment]
fair enough, I'll stick with the /wash characters in every url for now. Maybe in the future I'll just add a resource to my app at / that can serve up css, images, etc and just not use the default web server for this.
